services:
  orchestrator:
    build: .
    container_name: backuper
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL:-sqlite:////datosPersistentes/db/apps.db}"
    volumes:
      - backups:/backups
      - ./datosPersistentes/rcloneConfig:/config/rclone
      - ./datosPersistentes/db:/datosPersistentes/db
      - ${LOCAL_DIRECTORIES_ROOT:-./datosPersistentes/local-directories}:/local-directories
    networks:
      - backups_net
      - Backuper_tunn_net
volumes:
  backups:
networks:
  backups_net:
    driver: bridge
    name: backups_net
  Backuper_tunn_net:
    external: true
