services:
  orchestrator:
    build: .
    container_name: backuper
    env_file:
      - .env
    volumes:
      - backups:/backups
    networks:
      - backups_net
      - cloudflared_net
volumes:
  backups:
networks:
  backups_net:
    driver: bridge
    name: backups_net
  cloudflared_net:
    external: true
