services:
  orchestrator:
    build: .
    container_name: backuper

    volumes:
      - backups:/backups
    networks:
      - backups_net
volumes:
  backups:
networks:
  backups_net:
    driver: bridge
    name: backups_net
