services:
  orchestrator:
    build: .
    container_name: ${BACKUPER_CONTAINER_NAME:-backuper}
    env_file:
      - .env
    environment:
      DATABASE_URL: "${DATABASE_URL:-sqlite:////datosPersistentes/db/apps.db}"
      RCLONE_LOCAL_DIRECTORIES: "${RCLONE_LOCAL_DIRECTORIES:-/datosPersistentes/backups}"
    volumes:
      - ./datosPersistentes/rcloneConfig:/config/rclone
      - ./datosPersistentes/db:/datosPersistentes/db
      ${RCLONE_LOCAL_DIRECTORIES_VOLUME_MOUNTS:-      - ${RCLONE_LOCAL_DIRECTORIES:-./datosPersistentes/backups/}:${RCLONE_LOCAL_DIRECTORIES:-/datosPersistentes/backups}}
    networks:
      - backups_net
      - Backuper_tunn_net
networks:
  backups_net:
    driver: bridge
    name: backups_net
  Backuper_tunn_net:
    external: true
