services:
  backuper:
    build: .
    container_name: backuper
    ports:
      - "8000:8000"  # FastAPI API
      - "5550:5550"  # Flask UI
    volumes:
      - backups:/backups
    networks:
      - backups_net
networks:
  backups_net:
    driver: bridge
    name: backups_net
