services:
  orchestrator:
    build: .
    container_name: backuper
    env_file:
      - .env
    environment:
      DATABASE_URL: "sqlite:////sqlite/db/apps.db"
    volumes:
      - ./datosPersistentes/rcloneConfig:/config/rclone
      - ./datosPersistentes/db:/sqlite/db
      - ./datosPersistentes/backups:/backupsLocales
    networks:
      - backups_net
      - Backuper_tunn_net
networks:
  backups_net:
    driver: bridge
    name: backups_net
  Backuper_tunn_net:
    external: true
