services:
  backuper:
    build: .
    container_name: backuper
    volumes:
      - backups:/backups
    networks:
      - backups_net
networks:
  backups_net:
    driver: bridge
    name: backups_net
